resources:
  - name: build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artdisha
      buildName: mvn_example_build
      buildNumber: 1 
  - name: build_info_new
    type: BuildInfo
    configuration:
      sourceArtifactory: artdisha
      buildName: mvn_example_build
      buildNumber: 1
  - name: project_example
    type: GitRepo
    configuration:
      gitProvider:  github-disha
      path: dishameswania/project-examples
 
pipelines:
  - name: mvn_example_build
    steps:
      - name: build_mvn
        type: MvnBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
          sourceLocation: ./artifactory-maven-plugin-example
          mvnCommand: clean install -f ./pom.xml
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: project_example
          integrations:
            - name: artdisha
        execution:
          onStart:
            - _set_jdk openjdk8
            - javac -version
            - mvn --version
      - name: publish
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: build_mvn
          outputResources:
            - name: build_info
      - name: promote
        type: PromoteBuild
        configuration:
          targetRepository: libs-promoted-local
          includeDependencies: true
          inputSteps:
            - name: publish
          inputResources:
            - name: build_info
          outputResources:
            - name: build_info_new
      - name: xray
        type: XrayScan
        configuration:
          inputResources:
            - name: build_info_new
          outputResources:
            - name: build_info_new
